#!/usr/bin/env python3

import os
import sys
import sh
import requests

def prettify(line):
    ip = line.split(' ')[0]
    tag = line.split(' ')[6].split('?')[1] if '?' in line else 'unknown'

    return 'New visit from [{ip}](https://www.reg.ru/whois/?dname={ip}) with *{tag}* tag.\n\n`{line}`'.format(ip=ip, tag=tag.upper(), line=line)

def notify(tg_token, tg_chat_id, message):
    message = prettify(message)
    uri = 'https://api.telegram.org/bot' + tg_token + '/sendMessage'
    data = {
        'chat_id': tg_chat_id,
        'text': message,
        'parse_mode': 'Markdown',
        'disable_web_page_preview': True
    }
    res = requests.post(uri, data=data)
    return res

if __name__ == '__main__':
    try:
        log_path = os.environ['CV_WATCHDOG_LOG_PATH']
        uri_path = os.environ['CV_WATCHDOG_URI_PATH']
        ignore_list = os.environ['CV_WATCHDOG_IGNORE'] if 'CV_WATCHDOG_IGNORE' in os.environ else None
        tg_token = os.environ['CV_WATCHDOG_TG_TOKEN']
        tg_chat_id = os.environ['CV_WATCHDOG_TG_CHAT_ID']
    except KeyError as e:
        print('Could not proceed w/o required params, specify env var: {}'.format(e))
        sys.exit(1)

    print('args: {}; {}; {}; {}; {}'.format(log_path, uri_path, ignore_list, tg_token, tg_chat_id))

    print('Starting tail -f ...')
    # https://stackoverflow.com/a/12523119
    tail = sh.tail("-f", log_path, _iter=True)

    for line in tail:
        if uri_path in line:
            print(line.strip())

            show = True
            for ignore in ignore_list.split(','):
                if ignore in line:
                    show = False
                    continue
            if show:
                print('notify')
                notify(tg_token, tg_chat_id, line)
            else:
                print('ignored: {}'.format(ignore_list))
